spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
  jpa:
    generate-ddl: true
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  cache:
    cacheNames:
      - findBookByTitleAndAuthor
      - findBookByCategory
    caches:
      findBookByTitleAndAuthor:
        expiry: 1200s
      findBookByCategory:
        expiry: 1200s






